### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by MR-H0200** [robneville73/ember-cli-quaggajs#1]
Cannot read property 'replace' of undefined
```
TypeError: Cannot read property 'replace' of undefined
    at Class.massageVersionNumber (ember-cli-quaggajs/node_modules/ember-welcome-page/index.js:110:19)
    at Class.included (ember-cli-quaggajs/node_modules/ember-welcome-page/index.js:28:31)
    at Class.superWrapper [as included] (ember-cli-quaggajs/node_modules/core-object/lib/assign-properties.js:32:18)
    at EmberAddon.<anonymous> (ember-cli-quaggajs/node_modules/ember-cli/lib/broccoli/ember-app.js:469:15)
    at Array.filter (native)
    at EmberAddon.EmberApp._notifyAddonIncluded (ember-cli-quaggajs/node_modules/ember-cli/lib/broccoli/ember-app.js:464:45)
    at EmberAddon.EmberApp [as appConstructor] (ember-cli-quaggajs/node_modules/ember-cli/lib/broccoli/ember-app.js:137:8)
    at new EmberAddon (ember-cli-quaggajs/node_modules/ember-cli/lib/broccoli/ember-addon.js:33:8)
    at module.exports (ember-cli-quaggajs/ember-cli-build.js:6:13)
```

**Comment by robneville73** [comment]
Any context? What version of Ember, what you were trying to do etc?
